ImicAspnetMvc/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImicAspnetMvc.Database;
using ImicAspnetMvc.Models;

namespace ImicAspnetMvc.Controllers
{
    public class ArticleController : BaseController
    {
        public ActionResult Detail(int id)
        {
            //Request.QueryString["key1"] -> "value1"
            //Request.QueryString["key2"] -> "value2"

            if (id > 0) {                
                var dbContext = new ImicDataContext();
                var entity = dbContext.Articles.FirstOrDefault(e => e.Id == id);
                if(entity != null)
                {                    
                    SetPageTitle(entity.Title);

                    Session["ArticleId"] = id;

                    return View(new ArticleModel(entity));
                }                
            }
            return Redirect("/");
        } 
    }
}

ImicAspnetMvc/Controllers/HomeController.cs
using ImicAspnetMvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ImicAspnetMvc.Database;
using Newtonsoft.Json;
using System.Configuration;

namespace ImicAspnetMvc.Controllers
{
    public class HomeController : BaseController
    {        
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id">Category ID</param>
        /// <returns></returns>
        public ActionResult Index(int? id)
        {
            SetPageTitle("Home page");

            var configurationPageSize = ConfigurationManager.AppSettings["PageSize"]; // 10
            var domainName = ConfigurationManager.AppSettings["Domainname"]; // http://domain.name

            var model = new HomeModel {
                Heading = "Home",
                Articles = new List<ArticleListModel>()

            };
            var dbContext = new ImicDataContext();
            if (id > 0)
            {
                var category = dbContext.ArticleCategories.FirstOrDefault(e => e.Id == id);
                if (category != null)
                {
                    model.Heading = category.Name;
                    model.Articles = dbContext.Articles.Where(e => e.ArticleCategoryId == id).AsEnumerable().Select(e => new ArticleListModel(e)).ToList();
                }
            }
            else
            {
                model.Articles = dbContext.Articles.AsEnumerable().Select(e => new ArticleListModel(e)).ToList();
            }

            ViewBag.SessionArticleId = Session["ArticleId"];

            return View(model);
        }

        public ActionResult About(int id)
        {
            return View();
        }

        #region Partials

        public ActionResult SlidebarPartial()
        {
            var model = new SlidebarPartialModel()
            {
                Heading = "Categories",
                MostreadHeading = "Most read",
                Categories = new List<CategoryModel>(),
                MostreadArticles = new List<ArticleListModel>()
            };

            var dbContext = new ImicDataContext();
            model.Categories = dbContext.ArticleCategories.AsEnumerable().Select(e => new CategoryModel(e)).ToList();

            //most read articles

            model.MostreadArticles = dbContext.Articles.OrderByDescending(e => e.Id).Take(3).AsEnumerable().Select(e => new ArticleListModel(e)).ToList();
            
            return PartialView(model);
        }

        /// <summary>
        /// Hiện các bài đã xem gần đây, lấy từ cookies
        /// </summary>
        /// <returns></returns>
        public ActionResult ArticleRecentViewedPartial() {
            var model = new List<ArticleListModel>();

            var recentViewedCookies = Request.Cookies["RecentViewed"];// [ { id: 1, url: 'http://article.url' } ]
            if(recentViewedCookies != null && !string.IsNullOrWhiteSpace(recentViewedCookies.Value))
            {
                try
                {                    
                    var recentViewedArticles = 
                        JsonConvert.DeserializeObject<IEnumerable<ArticleRecentViewedModel>>(Server.UrlDecode(recentViewedCookies.Value));
                    var articleIds = new List<int>();
                    foreach(var item in recentViewedArticles)
                    {
                        articleIds.Add(item.id);
                    }

                    var dbContext = new ImicDataContext();

                    //model = dbContext.Articles
                    //    .Where(e => articleIds.Contains(e.Id))
                    //    .Select(e => new { e.Id, e.Sapo, e.Title }).AsEnumerable()
                    //    .Select(e => new ArticleListModel(e.Id, e.Title, e.Sapo)).ToList();

                    model = dbContext.Articles
                        .Where(e => articleIds.Contains(e.Id)).AsEnumerable()
                        .Select(e => new ArticleListModel(e)).ToList();
                }
                catch(Exception ex)
                {                    
                    Response.Cookies.Remove("RecentViewed");
                }
            }

            return PartialView(model);
        }

        #endregion
    }
}

ImicAspnetMvc/Views/Home/ArticleRecentViewedPartial.cshtml
@using ImicAspnetMvc.Models
@model IEnumerable<ArticleListModel>
@{
    if (Model == null)
    {
        return;
    }
}
<div class="row article-recent-viewed">
    @foreach (var article in Model)
    {
        <div class="col-sm-4">
            <a class="pull-left" href="@Url.Action("Detail", "Article", new { id = article.Id })">
                <img class="media-object" src="@article.Image" alt="@article.Title" title="@article.Title">
            </a>
            <div class="media-body">
                <h4 class="media-heading">@article.Title</h4>
                <p>@article.ShortDescription</p>
            </div>
        </div>
    }
</div>

ImicAspnetMvc/Views/Home/HomeMenuPartial.cshtml
<div class="navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Title</a>
        <ul class="nav navbar-nav">
            <li class="active">
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Link</a>
            </li>
        </ul>
    </div>
</div>

ImicAspnetMvc/Views/Home/Index.cshtml
@using ImicAspnetMvc.Models
@model HomeModel
@{
    //ViewBag.PageTitle = "Home Page";

    var sessionArticleId = ViewBag.SessionArticleId;
}
@section css {
<style>
    .homecsshere {
        font-size: 90px;
    }
    </style>
}
<div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title"><h3>@Model.Heading</h3></h3>
        </div>
        <div class="panel-body">
            @foreach (var article in Model.Articles)
            {
                <div class="panel">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        <a href="@Url.Action("Detail", "Article", new { id = article.Id })">
                        <strong>@article.Title</strong></a>
                    </h3>
                </div>
                <div class="panel-body">                    
                    @article.ShortDescription
                </div>
                <div class="panel-footer">
                    <a href="#">tag1</a> <a href="#">tag2</a>
                </div>
            </div>
            }            
        </div>
    </div>

@Html.Action("ArticleRecentViewedPartial", "Home", new { area = "" })

@if(sessionArticleId == null)
{
    <h4>
        Session expired
    </h4>
}
else {
    <h4>
         Session Article Id = @sessionArticleId        
    </h4>
}